version: '2'

services:
  api:
    build: './lighten-api'
    command: 'gunicorn gettingstarted.wsgi --log-file - --reload'
    working_dir: /app/user
    environment:
      PORT: 8080
      DATABASE_URL: 'postgres://postgres:@postgres:5432/postgres'
    ports:
      - "8080:8080"
    volumes:
      - './lighten-api:/app/user'
    depends_on:
      - postgres
  postgres:
    image: postgres:9
