version: '2'

services:
  api:
    build: .
    command: bin/start-api
    working_dir: /app/user
    environment:
      PORT: 8080
      DATABASE_URL: 'postgres://postgres:@postgres:5432/postgres'
    ports:
      - "8080:8080"
    volumes:
      - '.:/app/user'
    depends_on:
      - postgres
  postgres:
    image: postgres:9
